### ISSUE TITLE
Can't find M5_Network.

### ISSUE THREAD

**Issue by tdyHung** [Luo-Zhengding/SFANC-FxNLMS-ANC-Algorithm-based-on-Deep-Learning#3]
Greetings Luo Zhengding:

Base on Run Instructions: Run "Train_Testing_1D_Network.ipynb"，but it need M5_Network.py file in project.
Could you provide this file in gitlab?
Thank you,

```sh
from M5_Network import m3, m5, m11, m18, m34_res, m6_res
ModuleNotFoundError: No module named 'M5_Network'
```

**Comment by Luo-Zhengding** [comment]
Sorry, the file has been renamed. The M5_Network.py has been added.

**Comment by tdyHung** [comment]
Thank you for your prompt reply. 
Have a nice day.
