### ISSUE TITLE
How to measure the primary path and second path ?

### ISSUE THREAD

**Issue by JaySpeech** [Luo-Zhengding/SFANC-FxNLMS-ANC-Algorithm-based-on-Deep-Learning#8]
Thanks for you sharing.
Can you share us how to measure the primary and second path, Thank you.

**Comment by Luo-Zhengding** [comment]
Hello, thanks for your interest in our work.

In the training stage of the 1D network, the best control filters for different noises are decided using synthetic primary and secondary paths (band-pass filters). Thus, if there are some big differences of primary and secondary paths between training stage and test stage, the performance of SFANC algorithm will be influenced.

However, the FxNLMS algorithm can adaptively update the control filter’s coefficients even if the primary path and secondary path are changed. Therefore, in this case, the hybrid SFANC-FxNLMS algorithm will obtain a similar performance as FxNLMS algorithm. We can see it in Section 3. Noise reduction performance on the varying primary path.

**Comment by JaySpeech** [comment]
> 
Thanks for you reply.
I found another paper GFANC, if the primary path and secondary path is changed or different, the performance is similar to SFANC algorithm?
If we can measure a product's primary path and secondary path, the SFANC and GFANC will work better than FXLMS?
Maybe I understand wrong, Looking forward to your reply.

**Comment by Luo-Zhengding** [comment]
Thanks for your interest in our SFANC and GFANC works.

For dynamic noises, the SFANC and GFANC will outperform FxLMS. The details can be found in the paper. Thanks a lot.
________________________________
发件人: JaySpeech ***@***.***>
发送时间: 2023年7月28日 17:56
收件人: Luo-Zhengding/SFANC-FxNLMS-ANC-Algorithm-based-on-Deep-Learning ***@***.***>
抄送: #LUO ZHENGDING# ***@***.***>; Comment ***@***.***>
主题: Re: [Luo-Zhengding/SFANC-FxNLMS-ANC-Algorithm-based-on-Deep-Learning] How to measure the primary path and second path ? (Issue #8)


Thanks for you reply.
I found another paper <>, if the primary path and secondary path is changed or different, the performance is similar to SFANC algorithm?
If we can measure a product's primary path and secondary path, the SFANC and GFANC will work better than FXLMS?
Maybe I understand wrong, Looking forward to your reply.

―

**Comment by JaySpeech** [comment]
Thanks for your all reply.
